version: "2"
run:
  timeout: 3m
  relative-path-mode: gomod
  modules-download-mode: readonly

linters:
  default: standard
  enable:
    - revive
  disable:
    - errcheck
  settings:
    revive:
      enable-default-rules: true
      rules:
        - name: argument-limit
          arguments: [5]
        - name: unused-parameter
          arguments:
            - allow_regex: "^_"

issues:
  max-same-issues: 0
  max-issues-per-linter: 0